// @doors: 1, 2
// Door 3 N/A: buildVaultMap is a pure in-process string builder; reindex is
//   pure file scanning + rewriting. No subprocess spawn.
// Door 4 N/A: no message-queue interaction.
// Door 5 N/A: the vault map is a best-effort browse convenience — it emits no
//   NDJSON audit line (a map-write hiccup must never turn a capture into an
//   error, and it self-heals on the next reindex). Byte-stable regeneration is
//   verified by Door 1 + Door 2 assertions instead.

// Tests for Task 254 — the Obsidian vault map note (MAP.md).
//   - buildVaultMap(facts) is the PURE public boundary: parsed facts in, the
//     MAP.md markdown string out. Deterministic + byte-stable.
//   - reindex() writes MAP.md alongside INDEX.md from the same walk.
//
// Boundary-test discipline: test the buildVaultMap() + reindex() PUBLIC
// contract — the rendered wikilink shape, edge rendering, grouping, sort order,
// byte-stability — NOT internal helpers (slug resolution maps, the regex).

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import {
  mkdtempSync,
  rmSync,
  existsSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  readdirSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { buildVaultMap, MAP_ANCHOR_CITERS_SHOWN } from '../packages/cli/src/vault-map.mjs';
import { MAP_FILENAME } from '../packages/cli/src/fact-store.mjs';
import { reindex } from '../packages/cli/src/reindex.mjs';
import { writeFact } from '../packages/cli/src/write-fact.mjs';

// A parsed-fact object of the shape fact-store's eachFactIn yields, minimal for
// the pure builder.
function fact({ id, filename, title, related, superseded_by, body = '' }) {
  const frontmatter = { id, title };
  if (related !== undefined) frontmatter.related = related;
  if (superseded_by !== undefined) frontmatter.superseded_by = superseded_by;
  return { id, filename, frontmatter, body };
}

function validFactOpts(overrides = {}) {
  return {
    tier: 'P',
    type: 'feedback',
    slug: 'sample',
    title: 'Sample fact',
    body: 'This is the body of the sample fact.',
    writeSource: 'user-explicit',
    trust: 'high',
    sourceFile: 'context/transcripts/2026-05-24.md',
    sourceLine: 1,
    sourceSha1: 'deadbeef0123456789abcdef0123456789abcdef',
    ...overrides,
  };
}

describe('Task 254 — buildVaultMap() pure boundary', () => {
  // ---- Door 1: Response (the returned string's shape) ----

  it('empty corpus → header + generated banner + Facts: 0, no group headings', () => {
    const out = buildVaultMap([], { tier: 'P' });
    expect(out).toContain('# Memory vault map — project tier');
    expect(out).toContain('GENERATED by `cmk reindex`');
    expect(out).toContain('Facts: 0');
    expect(out).not.toContain('## '); // no type-group headings
    // byte-stable: two builds of the same (empty) corpus are identical
    expect(buildVaultMap([], { tier: 'P' })).toBe(out);
  });

  it('renders each fact as a [[type_slug]] wikilink resolving to its filename', () => {
    const facts = [
      fact({ id: 'P-AAAAAAAA', filename: 'feedback_webcam-roi.md', title: 'Webcam ROI' }),
      fact({ id: 'P-BBBBBBBB', filename: 'project_auto-roi.md', title: 'Auto-ROI notes' }),
    ];
    const out = buildVaultMap(facts, { tier: 'P' });
    // wikilink target is the filename basename (no .md) — Obsidian resolves it
    expect(out).toContain('[[feedback_webcam-roi]]');
    expect(out).toContain('[[project_auto-roi]]');
    // title trails the link as plain text (an em-dash separator), never inside [ ]
    expect(out).toContain('[[feedback_webcam-roi]] — Webcam ROI');
    expect(out).toContain('Facts: 2');
  });

  it('groups by type heading, types alphabetical, facts id-sorted within a type', () => {
    const facts = [
      fact({ id: 'P-ZZZZZZZZ', filename: 'project_beta.md', title: 'Beta' }),
      fact({ id: 'P-AAAAAAAA', filename: 'project_alpha.md', title: 'Alpha' }),
      fact({ id: 'P-MMMMMMMM', filename: 'feedback_x.md', title: 'X' }),
    ];
    const out = buildVaultMap(facts, { tier: 'P' });
    const feedbackIdx = out.indexOf('## feedback');
    const projectIdx = out.indexOf('## project');
    expect(feedbackIdx).toBeGreaterThan(-1);
    expect(projectIdx).toBeGreaterThan(-1);
    // feedback sorts before project (alphabetical type groups)
    expect(feedbackIdx).toBeLessThan(projectIdx);
    // within project, id P-AAAAAAAA (alpha) before P-ZZZZZZZZ (beta)
    expect(out.indexOf('[[project_alpha]]')).toBeLessThan(out.indexOf('[[project_beta]]'));
  });

  it('renders related frontmatter slugs AND body [[slug]] wikilinks as resolved [[type_slug]] links, deduped + sorted', () => {
    const facts = [
      fact({
        id: 'P-AAAAAAAA',
        filename: 'feedback_webcam-roi.md',
        title: 'Webcam ROI',
        related: ['auto-roi'],
        body: 'See [[stability]] for details, and [[auto-roi]] again.',
      }),
      fact({ id: 'P-BBBBBBBB', filename: 'project_auto-roi.md', title: 'Auto-ROI notes' }),
      fact({ id: 'P-CCCCCCCC', filename: 'reference_stability.md', title: 'Stability detector' }),
    ];
    const out = buildVaultMap(facts, { tier: 'P' });
    // both the frontmatter `related` slug and the body wikilink resolve, on one related line
    expect(out).toMatch(/related: \[\[project_auto-roi\]\], \[\[reference_stability\]\]/);
    // the duplicate [[auto-roi]] body ref does NOT double the target
    const relLine = out.split('\n').find((l) => l.includes('related:'));
    expect(relLine.match(/project_auto-roi/g)).toHaveLength(1);
  });

  it('renders superseded_by via the live successor filename when present, else the bare [[id]]', () => {
    const facts = [
      fact({
        id: 'P-AAAAAAAA',
        filename: 'feedback_old.md',
        title: 'Old fact',
        superseded_by: 'P-BBBBBBBB',
      }),
      fact({ id: 'P-BBBBBBBB', filename: 'feedback_new.md', title: 'New fact' }),
      fact({
        id: 'P-CCCCCCCC',
        filename: 'feedback_gone.md',
        title: 'Superseded by an archived fact',
        superseded_by: 'P-DDDDDDDD', // successor moved to archive/ — not in the live set
      }),
    ];
    const out = buildVaultMap(facts, { tier: 'P' });
    // live successor → resolves to its type_slug filename
    expect(out).toContain('superseded by: [[feedback_new]]');
    // archived/absent successor → the bare id wikilink (resolves via the id alias
    // once the successor carries one; a phantom otherwise — honest, never dropped)
    expect(out).toContain('superseded by: [[P-DDDDDDDD]]');
  });

  it('drops self-references and unresolved related slugs render as plain code text (no phantom edge)', () => {
    const facts = [
      fact({
        id: 'P-AAAAAAAA',
        filename: 'project_self.md',
        title: 'Self and dangling',
        related: ['self', 'does-not-exist'],
        body: 'A [[self]] ref should not self-link.',
      }),
    ];
    const out = buildVaultMap(facts, { tier: 'P' });
    // self-reference dropped: the only [[project_self]] occurrence is the fact's own heading link
    expect(out.match(/\[\[project_self\]\]/g)).toHaveLength(1);
    // dangling slug kept visible but NOT as a wikilink (no phantom graph node)
    expect(out).toContain('`does-not-exist`');
    expect(out).not.toContain('[[does-not-exist]]');
  });

  it('collapses whitespace/newlines in titles so each fact stays one line', () => {
    const facts = [
      fact({ id: 'P-AAAAAAAA', filename: 'project_x.md', title: 'A title\nwith  a newline' }),
    ];
    const out = buildVaultMap(facts, { tier: 'P' });
    expect(out).toContain('[[project_x]] — A title with a newline');
  });

  it('is byte-stable: two builds over the same corpus produce identical bytes regardless of input order', () => {
    const a = fact({ id: 'P-AAAAAAAA', filename: 'project_a.md', title: 'A', related: ['b'] });
    const b = fact({ id: 'P-BBBBBBBB', filename: 'project_b.md', title: 'B' });
    expect(buildVaultMap([a, b], { tier: 'P' })).toBe(buildVaultMap([b, a], { tier: 'P' }));
  });
});

describe('Task 254 — reindex() writes MAP.md alongside INDEX.md', () => {
  let sandbox;
  let projectRoot;
  let userDir;
  let memDir;

  beforeEach(() => {
    sandbox = mkdtempSync(join(tmpdir(), 'cmk-vaultmap-test-'));
    projectRoot = join(sandbox, 'proj');
    userDir = join(sandbox, 'user-tier');
    memDir = join(projectRoot, 'context', 'memory');
  });

  afterEach(() => {
    rmSync(sandbox, { recursive: true, force: true });
  });

  it('Door 1: reindex returns the mapPath; Door 2: MAP.md exists with the fact as a wikilink', () => {
    writeFact(validFactOpts({ projectRoot, slug: 'alpha', title: 'Alpha fact' }));
    const result = reindex({ tier: 'P', projectRoot, userDir, warn: () => {} });
    expect(result.mapPath).toBe(join(memDir, MAP_FILENAME));
    expect(existsSync(result.mapPath)).toBe(true);
    const map = readFileSync(result.mapPath, 'utf8');
    expect(map).toContain('[[feedback_alpha]]');
    expect(map).toContain('Facts: 1');
  });

  it('Door 1: a map-write FAILURE degrades to a warning — mapBytes null, INDEX.md still written, reindex still succeeds (review finding #2)', () => {
    writeFact(validFactOpts({ projectRoot, slug: 'alpha', title: 'Alpha fact' }));
    // Force writeFileSync(mapPath) to throw: occupy the MAP.md path with a DIRECTORY.
    rmSync(join(memDir, MAP_FILENAME), { force: true });
    mkdirSync(join(memDir, MAP_FILENAME));
    const warnings = [];
    const result = reindex({ tier: 'P', projectRoot, userDir, warn: (m) => warnings.push(m) });
    expect(result.mapBytes).toBeNull();
    expect(warnings.some((w) => w.includes(MAP_FILENAME))).toBe(true);
    // the failure is CONTAINED: the index write and fact count are unaffected
    expect(existsSync(result.indexPath)).toBe(true);
    expect(result.factCount).toBe(1);
  });

  it('MAP.md is not itself indexed as a fact (INDEX.md never lists it; reindex emits no warning for it)', () => {
    writeFact(validFactOpts({ projectRoot, slug: 'alpha', title: 'Alpha' }));
    const warnings = [];
    const result = reindex({ tier: 'P', projectRoot, userDir, warn: (m) => warnings.push(m) });
    const index = readFileSync(result.indexPath, 'utf8');
    expect(index).not.toContain(MAP_FILENAME);
    expect(index).not.toContain('Memory vault map');
    // no "skipped — missing frontmatter" warning about MAP.md
    expect(warnings.some((w) => w.includes(MAP_FILENAME))).toBe(false);
    // the fact count reflects only real facts, not MAP.md
    expect(result.factCount).toBe(1);
  });

  it('over-mutation: regenerating MAP.md does not touch any fact file, and byte-stable across reindexes', () => {
    writeFact(validFactOpts({ projectRoot, slug: 'alpha', title: 'Alpha' }));
    writeFact(validFactOpts({ projectRoot, slug: 'beta', title: 'Beta', body: 'A different body.' }));
    reindex({ tier: 'P', projectRoot, userDir, warn: () => {} });

    // snapshot every fact file's bytes
    const factNames = readdirSync(memDir).filter((n) => n.endsWith('.md') && n !== 'INDEX.md' && n !== 'MAP.md' && n !== MAP_FILENAME);
    expect(factNames.length).toBe(2);
    const before = Object.fromEntries(factNames.map((n) => [n, readFileSync(join(memDir, n), 'utf8')]));
    const map1 = readFileSync(join(memDir, MAP_FILENAME), 'utf8');

    // regenerate
    reindex({ tier: 'P', projectRoot, userDir, warn: () => {} });

    const map2 = readFileSync(join(memDir, MAP_FILENAME), 'utf8');
    expect(map2).toBe(map1); // byte-stable regeneration
    for (const n of factNames) {
      expect(readFileSync(join(memDir, n), 'utf8')).toBe(before[n]); // fact files untouched
    }
  });

  it('a hand-edited MAP.md is fully overwritten on reindex (generated, not authoritative)', () => {
    writeFact(validFactOpts({ projectRoot, slug: 'alpha', title: 'Alpha' }));
    reindex({ tier: 'P', projectRoot, userDir, warn: () => {} });
    const mapPath = join(memDir, MAP_FILENAME);
    writeFileSync(mapPath, 'hand-edited garbage', 'utf8');
    reindex({ tier: 'P', projectRoot, userDir, warn: () => {} });
    const map = readFileSync(mapPath, 'utf8');
    expect(map).not.toContain('garbage');
    expect(map).toContain('[[feedback_alpha]]');
  });
});

// Task 256 — the `## Cited anchors` constellation section: decision/task/ADR
// anchors densely cited across fact bodies become browsable hubs in the map.
describe('Task 256 — buildVaultMap() anchor constellations', () => {
  // A 4-fact corpus → df-ceiling floor(4*0.5)=2, so an anchor cited by exactly
  // 2 facts qualifies (at-cap) and a 1-citer anchor is below the floor.
  function corpus() {
    return [
      fact({ id: 'P-2DZG7XF4', filename: 'feedback_a.md', title: 'A', body: 'per D-361 and Task 232 we shipped' }),
      fact({ id: 'P-34GZDKAW', filename: 'feedback_b.md', title: 'B', body: 'D-361 is load-bearing per ADR-0023' }),
      fact({ id: 'P-56UXMRD6', filename: 'feedback_c.md', title: 'C', body: 'this fact cites D-999 alone' }),
      fact({ id: 'P-D6YL7RBC', filename: 'feedback_d.md', title: 'D', body: 'no anchors here' }),
    ];
  }

  it('renders a Cited anchors section with each qualifying anchor + its citing facts', () => {
    const out = buildVaultMap(corpus(), { tier: 'P' });
    expect(out).toContain('## Cited anchors');
    // D-361 cited by facts a + b → a hub with both as wikilinks.
    expect(out).toContain('- **D-361** ← [[feedback_a]], [[feedback_b]]');
  });

  it('omits a single-citer anchor (below MIN_ANCHOR_CITERS floor)', () => {
    const out = buildVaultMap(corpus(), { tier: 'P' });
    // D-999 + Task-232 + ADR-0023 are each cited by only one fact → no hub.
    expect(out).not.toContain('D-999');
    expect(out).not.toContain('Task-232');
    expect(out).not.toContain('ADR-0023');
  });

  it('no qualifying anchors → no Cited anchors section', () => {
    const out = buildVaultMap(
      [fact({ id: 'P-2DZG7XF4', filename: 'feedback_a.md', title: 'A', body: 'plain, no anchors' })],
      { tier: 'P' },
    );
    expect(out).not.toContain('## Cited anchors');
  });

  it('the anchor section is byte-stable across rebuilds', () => {
    expect(buildVaultMap(corpus(), { tier: 'P' })).toBe(buildVaultMap(corpus(), { tier: 'P' }));
  });

  it('a doc-anchor citing INSIDE code does not become a hub', () => {
    const facts = [
      fact({ id: 'P-2DZG7XF4', filename: 'feedback_a.md', title: 'A', body: 'literal `D-361` in code' }),
      fact({ id: 'P-34GZDKAW', filename: 'feedback_b.md', title: 'B', body: '```\nD-361 fenced\n```' }),
    ];
    const out = buildVaultMap(facts, { tier: 'P' });
    expect(out).not.toContain('## Cited anchors');
  });
});

// Task 256 — the render-only per-anchor citer cap (review finding 4). The edges
// table + `cmk links` carry every citer; MAP.md bounds the human-browsable list.
describe('Task 256 — anchor render cap MAP_ANCHOR_CITERS_SHOWN', () => {
  // Deterministic unique valid-shaped ids (programmatic → no validate-test-ids trip).
  const ALPHABET = '23456789ABCDEFGHJKLMNPQRSTUVWXYZa';
  const mkId = (n) => {
    let x = n;
    let s = '';
    for (let i = 0; i < 8; i++) {
      s = ALPHABET[x % 32] + s;
      x = Math.floor(x / 32);
    }
    return `P-${s}`;
  };
  // n facts each citing D-5, plus padding so the anchor clears the df-ceiling.
  function corpus(n) {
    const facts = [];
    for (let i = 0; i < n; i++) {
      facts.push(fact({ id: mkId(i), filename: `feedback_c${i}.md`, title: `C${i}`, body: 'cites D-5' }));
    }
    for (let i = 0; i < n + 5; i++) {
      facts.push(fact({ id: mkId(1000 + i), filename: `feedback_p${i}.md`, title: `P${i}`, body: 'plain fact' }));
    }
    return facts;
  }
  const anchorLine = (out) => out.split('\n').find((l) => l.startsWith('- **D-5**'));

  it('at-cap: exactly MAP_ANCHOR_CITERS_SHOWN citers → all shown, no "and N more"', () => {
    expect(MAP_ANCHOR_CITERS_SHOWN).toBe(20);
    const line = anchorLine(buildVaultMap(corpus(20), { tier: 'P' }));
    expect((line.match(/\[\[/g) || []).length).toBe(20);
    expect(line).not.toContain('more');
  });

  it('over-cap: 21 citers → 20 shown + "… and 1 more"', () => {
    const line = anchorLine(buildVaultMap(corpus(21), { tier: 'P' }));
    expect((line.match(/\[\[/g) || []).length).toBe(20);
    expect(line).toContain('… and 1 more');
  });

  it('the capped render is byte-stable across rebuilds', () => {
    expect(buildVaultMap(corpus(30), { tier: 'P' })).toBe(buildVaultMap(corpus(30), { tier: 'P' }));
  });
});
