// vault-map.mjs — the Obsidian vault map note (Task 254, D-397 companion to the
// own-UI viewer / Task 255).
//
// `context/memory/` is already markdown + frontmatter, so Obsidian opens it as a
// vault for free. What Obsidian's graph/backlinks need to LIGHT UP is resolvable
// links — and the existing corpus's own edges don't resolve on their own: fact
// files are named `<type>_<slug>.md`, but the edges the kit writes reference the
// bare `<slug>` (`related:` frontmatter, `[[slug]]` body wikilinks) or an id
// (`superseded_by`), none of which Obsidian resolves to a `<type>_<slug>.md`
// file by default. Rewriting 2,000 committed fact files to fix that is a
// migration we deliberately do NOT do (Task 254 hard constraint).
//
// Instead: a SINGLE GENERATED map note that renders every fact as a resolvable
// `[[<type>_<slug>]]` wikilink (the filename basename Obsidian DOES resolve) with
// its edges rendered as links too. It lights up the whole corpus graph WITHOUT
// touching any fact file — a pure EXPORT-FORMAT over the same markdown reindex
// already walks (ADR-0002: markdown is the only source of truth; this note is a
// derived, regenerable view, exactly like INDEX.md). Written by reindex.mjs
// beside INDEX.md; byte-stable so two rebuilds over the same corpus are identical.
//
// SHARED-MODULE DISCIPLINE (CLAUDE.md): edge extraction reuses graph-index's
// pure parsers (`extractWikilinks`, `relatedSlugs`, `slugForFactFilename`) — the
// SAME relation model the `edges` table is built from (Task 232) — never a
// re-rolled regex. This is a pure string builder: no file IO, no DB.

import { extractWikilinks, relatedSlugs, slugForFactFilename } from './graph-index.mjs';

const TIER_LABEL = {
  P: 'project tier',
  L: 'local tier',
  U: 'user tier',
};

// Recover the fact `type` from a `<type>_<slug>.md` filename for grouping.
// Anything without a known type prefix groups under `other` (defensive — the
// walk only yields real fact files, but a hand-dropped file shouldn't crash).
const FACT_TYPE_PREFIX = /^(user|feedback|project|reference|judgment)_/;
function typeForFilename(filename) {
  const m = String(filename).match(FACT_TYPE_PREFIX);
  return m ? m[1] : 'other';
}

/** Filename basename (no `.md`) — the wikilink target Obsidian resolves. */
function basenameNoExt(filename) {
  return String(filename).replace(/\.md$/i, '');
}

/** Collapse internal whitespace so a multi-line title stays one map line. */
function oneLine(text) {
  return String(text ?? '').replace(/\s+/g, ' ').trim();
}

/**
 * Build the MAP.md content for one tier's fact corpus. Pure + deterministic.
 *
 * @param {Array<{id: string, filename: string, frontmatter: object, body: string}>} facts
 *   Parsed facts (the shape fact-store's `eachFactIn` yields). Tombstoned/
 *   malformed facts should already be filtered by the caller (reindex does).
 * @param {object} [opts]
 * @param {'P'|'L'|'U'} [opts.tier='P']
 * @returns {string} the MAP.md markdown
 */
export function buildVaultMap(facts, { tier = 'P' } = {}) {
  // Resolution maps built from the live corpus (first writer of a key wins, matching
  // graph-index's slug→id map precedence). slug → basename and id → basename let a
  // `related`/`[[slug]]` reference or a `superseded_by` id resolve to a link target.
  const slugToBase = new Map();
  const idToBase = new Map();
  for (const f of facts) {
    const base = basenameNoExt(f.filename);
    const slug = slugForFactFilename(f.filename);
    if (slug && !slugToBase.has(slug)) slugToBase.set(slug, base);
    if (f.id && !idToBase.has(f.id)) idToBase.set(f.id, base);
  }

  // Group facts by type, then sort types alphabetically and facts by id within a
  // type — a pure function of the on-disk corpus (byte-stable across rebuilds).
  const byType = new Map();
  for (const f of facts) {
    const t = typeForFilename(f.filename);
    if (!byType.has(t)) byType.set(t, []);
    byType.get(t).push(f);
  }
  const types = [...byType.keys()].sort();

  const lines = [];
  lines.push(`# Memory vault map — ${TIER_LABEL[tier] ?? 'project tier'}`);
  lines.push('');
  lines.push('<!-- GENERATED by `cmk reindex` — do not edit; rewritten on every memory write. -->');
  lines.push('<!-- Browse this folder as an Obsidian vault. Each [[link]] opens a fact file. -->');
  lines.push('<!-- How to open + the read-vs-write rule: docs/OBSIDIAN.md -->');
  lines.push('');
  lines.push(`Facts: ${facts.length}`);

  for (const t of types) {
    const group = byType.get(t).slice().sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
    lines.push('');
    lines.push(`## ${t}`);
    lines.push('');
    for (const f of group) {
      const selfBase = basenameNoExt(f.filename);
      lines.push(`- [[${selfBase}]] — ${oneLine(f.frontmatter?.title) || '(untitled)'}`);

      // Relation axis = `related:` frontmatter ∪ body `[[slug]]` wikilinks (the
      // SAME union graph-index surfaces as a fact's out-neighbourhood). Resolve
      // each slug to a link target; a slug pointing back at THIS fact is a
      // self-edge (dropped); a resolved target renders as a wikilink; an
      // unresolved (dangling) slug renders as plain code text — visible but not a
      // phantom graph node.
      const relSlugs = [];
      const seenSlug = new Set();
      for (const s of [...relatedSlugs(f.frontmatter?.related), ...extractWikilinks(f.body)]) {
        if (!seenSlug.has(s)) {
          seenSlug.add(s);
          relSlugs.push(s);
        }
      }
      const relRendered = [];
      const seenTarget = new Set();
      for (const s of relSlugs) {
        const base = slugToBase.get(s);
        if (base) {
          if (base === selfBase) continue; // self-edge
          if (seenTarget.has(base)) continue;
          seenTarget.add(base);
          relRendered.push({ resolved: true, text: base });
        } else {
          relRendered.push({ resolved: false, text: s });
        }
      }
      // Sort for byte-stability: resolved links first (alpha), dangling last (alpha).
      relRendered.sort((a, b) => {
        if (a.resolved !== b.resolved) return a.resolved ? -1 : 1;
        return a.text < b.text ? -1 : a.text > b.text ? 1 : 0;
      });
      if (relRendered.length) {
        const rendered = relRendered
          .map((r) => (r.resolved ? `[[${r.text}]]` : `\`${r.text}\``))
          .join(', ');
        lines.push(`  - related: ${rendered}`);
      }

      // Supersession: `superseded_by` is an id. Resolve to the live successor's
      // filename when it's in the corpus; else emit the bare `[[id]]` (resolves
      // via the successor's id alias — Task 254 shape a — or shows as a phantom,
      // honest either way; a superseded fact is MOVED to archive/ so its
      // successor may legitimately not be in this walk).
      const sup = f.frontmatter?.superseded_by;
      if (typeof sup === 'string' && sup.trim()) {
        const base = idToBase.get(sup.trim());
        lines.push(`  - superseded by: [[${base ?? sup.trim()}]]`);
      }
    }
  }

  return lines.join('\n') + '\n';
}
